# Whether this GitHub repo is engineering related
engineering_project: true
# Name of the repository/project in English
english_name: Creative Commons SaltStack
# All technologies used
technologies: Python, SaltStack
# Whether this repository should be featured on the CC Open Source site
featured: false
