#######################################################################
# Wiki.js - CONFIGURATION                                             #
#######################################################################
# Full explanation + examples in the documentation:
# https://docs-legacy.requarks.io/wiki/install/configuration
# You can use an ENV variable by using $(ENV_VAR_NAME) as the value

# ---------------------------------------------------------------------
# Title of this site
# ---------------------------------------------------------------------

title: CC Internal Wiki

# ---------------------------------------------------------------------
# Full public path to the site, without the trailing slash
# ---------------------------------------------------------------------
# INCLUDE CLIENT PORT IF NOT 80/443!

host: 'https://wikijs.creativecommons.org'

# ---------------------------------------------------------------------
# Port the main server should listen to (80 by default)
# ---------------------------------------------------------------------
# To use process.env.PORT, comment the line below:

port: 8080

# ---------------------------------------------------------------------
# Data Directories
# ---------------------------------------------------------------------

paths:
  repo: ./repo
  data: ./data

# ---------------------------------------------------------------------
# Upload Limits
# ---------------------------------------------------------------------
# In megabytes (MB)

uploads:
  maxImageFileSize: 3
  maxOtherFileSize: 100

# ---------------------------------------------------------------------
# Site Language
# ---------------------------------------------------------------------
# Possible values: en, de, es, fa, fr, ja, ko, nl, pt, ru, sr, sv, tr or zh

lang: en

# Enable for right to left languages (e.g. arabic):
langRtl: false

# ---------------------------------------------------------------------
# Site Authentication
# ---------------------------------------------------------------------

public: false

auth:
  defaultReadAccess: true
  local:
    # This appears to be required by ldap
    enabled: true
  google:
    # Google+ Sign-In will expire in March 2019
    # https://github.com/Requarks/wiki-v1/issues/146
    #
    # https://docs-legacy.requarks.io/wiki/install/authentication#google-id
    enabled: false
  microsoft:
    enabled: false
  facebook:
    enabled: false
  github:
    enabled: false
  slack:
    enabled: false
  ldap:
    # https://docs-legacy.requarks.io/wiki/install/authentication#ldap-active-directory
    enabled: true
    url: 'ldap://127.0.0.1:1636'
    bindDn: {{ pillar.stunnel4.gsuite_ldap_user }}
    bindCredentials: {{ pillar.stunnel4.gsuite_ldap_pass }}
    searchBase: 'ou=Users,dc=creativecommons,dc=org'
    {% raw %}searchFilter: '(mail={{username}})'{% endraw %}
  azure:
    enabled: false
  oauth2:
    enabled: false
  oidc:
    enabled: false

# ---------------------------------------------------------------------
# Secret key to use when encrypting sessions
# ---------------------------------------------------------------------
# Use a long and unique random string (256-bit keys are perfect!)

sessionSecret: {{ pillar.wikijs.session_secret }}

# ---------------------------------------------------------------------
# Database Connection String
# ---------------------------------------------------------------------

db: 'mongodb://localhost:27017/wiki'

# ---------------------------------------------------------------------
# Git Connection Info
# ---------------------------------------------------------------------

git:
  url: '{{ pillar.wikijs.git_url }}'
  branch: {{ pillar.wikijs.git_branch }}
  auth:
    type: ssh
    privateKey: /srv/wikijs/{{ pillar.wikijs.git_ssh_key }}
    sslVerify: true
  showUserEmail: true
  serverEmail: {{ pillar.wikijs.git_server_email }}

# ---------------------------------------------------------------------
# Features
# ---------------------------------------------------------------------
# You can enable / disable specific features below

features:
  linebreaks: true
  mathjax: true

# ---------------------------------------------------------------------
# External Logging
# ---------------------------------------------------------------------

externalLogging:
  bugsnag: false
  loggly: false
  papertrail: false
  rollbar: false
  sentry: false

# ---------------------------------------------------------------------
# Color Theme
# ---------------------------------------------------------------------

theme:
  primary: deep-orange
  alt: grey
  viewSource: all # all | write | false
  footer: grey
  code:
    dark: true
    colorize: true

